### ISSUE TITLE
Sourcemap support using the purs-loader and purescript-webpack-plugin

### ISSUE THREAD

**Issue by ethul** [nwolverson/purescript-sourcemap-test#1]
This isn't an issue, but I wanted to mention that I've added an example of sourcemap support in case you are interested.

https://github.com/ethul/purescript-webpack-example

Note that to support this, the `purs-loader@0.6.0-beta.5` and `purescript-webpack-plugin@0.2.0-beta.6` must be used.

**Comment by nwolverson** [comment]
Cool! I thought the webpack plugin going through psc-bundle would be a blocker for this, I see you've made it optional. I'll fire a link to that example on the README.

**Comment by ethul** [comment]
Great. Thanks!
